In [36]:
# Load library
import numpy as np
from scipy import sparse
from sklearn.feature_extraction import DictVectorizer

In [17]:
# Create vector
vector = np.array([1, 2, 3, 4, 5, 6])
vector

array([1, 2, 3, 4, 5, 6])

In [18]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# Tranpose vector
vector.T

array([1, 2, 3, 4, 5, 6])

In [20]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Selecting Elements In An Array

In [21]:
# Select second element
vector[1]

2

In [22]:
# Select second row, second column
matrix[1,1]

5

In [23]:
# Create matrix
tensor = np.array([
                    [[[1, 1], [1, 1]], [[2, 2], [2, 2]]],
                    [[[3, 3], [3, 3]], [[4, 4], [4, 4]]]
                  ])
tensor

array([[[[1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2]]],


       [[[3, 3],
         [3, 3]],

        [[4, 4],
         [4, 4]]]])

In [24]:
tensor[0,1,0]

array([2, 2])

Create A Sparse Matrix:In numerical analysis and scientific computing, a sparse matrix or sparse array is a matrix in which most of the elements are zero. By contrast, if most of the elements are nonzero, then the matrix is considered dense.

In [31]:
# Create a matrix
mat = np.array([[0, 0],
                   [0, 1],
                   [2, 0]])

In [30]:
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(mat)
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int32'>'
	with 1 stored elements in Compressed Sparse Row format>

In [32]:
# Create a 4x3 matrix
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

In [35]:
# Reshape matrix into 2x6 matrix:The new shape should be compatible with the original shape
matrix1.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Converting A Dictionary Into A Matrix

In [37]:
# Our dictionary of data
data_dict = [{'Red': 2, 'Blue': 4},
             {'Red': 4, 'Blue': 3},
             {'Red': 1, 'Yellow': 2},
             {'Red': 2, 'Yellow': 2}]

In [38]:
# Create DictVectorizer object
dictvectorizer = DictVectorizer(sparse=False)

# Convert dictionary into feature matrix
features = dictvectorizer.fit_transform(data_dict)

# View feature matrix
features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

In [39]:
# View feature matrix column names
dictvectorizer.get_feature_names()

['Blue', 'Red', 'Yellow']

In [40]:
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [41]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [42]:
# Calculate the trace of the matrix
matrix.diagonal().sum()

15

In [43]:
# Return diagonal elements
matrix.diagonal()

array([1, 5, 9])

In [44]:
# Return determinant of matrix
np.linalg.det(matrix)

0.0

Flatten matrix :Return a copy of the array collapsed into one dimension.

In [45]:
# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# Return mean
np.mean(matrix)

5.0

In [47]:
# Return variance
np.var(matrix)

6.666666666666667

In [48]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [49]:
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

In [50]:
# Return maximum element
np.max(matrix)

9

In [51]:
# Return minimum element
np.min(matrix)

1

In [52]:
# Find the maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [53]:
# Find the maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

In [54]:
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [55]:
# Calculate dot product
vector_a @ vector_b

32

In [56]:
# View number of rows and columns
matrix.shape

(3, 3)

In [57]:
# View number of elements (rows * columns)
matrix.size

9

In [58]:
# View number of dimensions
matrix.ndim

2

In [59]:
tensor = np.array([
                    [[[1, 1], [1, 1]], [[2, 2], [2, 2]]],
                    [[[3, 3], [3, 3]], [[4, 4], [4, 4]]]
                  ])

In [60]:
tensor.ndim

4

In [61]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [62]:
# Create a function that adds 100 to something
add_100 = lambda i: i + 100

# Create a vectorized function
vectorized_add_100 = np.vectorize(add_100)

In [63]:
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [64]:
# Create a vector as a row
vector_row = np.array([1, 2, 3])

In [66]:
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])
vector_column

array([[1],
       [2],
       [3]])

In [67]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

In [68]:
# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [69]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])